---
pre_commits:
  # GitHooks::PreCommit::TrailingWhitespace:
  # GitHooks::PreCommit::PreventDebugger:
  # GitHooks::PreCommit::Rubocop:
  #   use_stash: false
  # GitHooks::PreCommit::Rspec:
  GitHooks::PreCommit::PreventMaster:
